### ISSUE TITLE
Terminal colours seem off 

### ISSUE THREAD

**Issue by FredHappyface** [Binaryify/OneDark-Pro#382]
This may be a largely personal thing (to me that is) but the terminal colours seem off compared to other one dark terminal themes such as the konsole theme 

VsCode:

![image](https://user-images.githubusercontent.com/41634689/78784085-9c28cc80-799c-11ea-9be8-ea13bd19bddd.png)
![image](https://user-images.githubusercontent.com/41634689/78784868-01c98880-799e-11ea-96c0-71df070cd1bf.png)

Konsole:

![image](https://user-images.githubusercontent.com/41634689/78784045-8c10ed00-799c-11ea-892a-a7e59a189fb4.png)
![image](https://user-images.githubusercontent.com/41634689/78784828-f5ddc680-799d-11ea-94ee-4cbe384e4960.png)

Would like to add what a great project this is :smile:

**Comment by Binaryify** [comment]
I don't know how to reproduce it, could you provide some way?
![image](https://user-images.githubusercontent.com/12221718/82149868-ee0d1e00-9889-11ea-93d3-b38095281cc7.png)

**Comment by FredHappyface** [comment]
Here is some code that produces the output below:

Powershell
```powershell
Write-Output "$([char]27)[35mMagenta$([char]27)[00m|$([char]27)[95mBrightMagenta$([char]27)[00m" 
```

Bash
```bash
echo -e '\033[35mMagenta\033[00m|\033[95mBrightMagenta\033[00m'
```

And here is the actual output:
![image](https://user-images.githubusercontent.com/41634689/82253274-91246d00-9948-11ea-9181-e39b1db9bdb0.png)

^ This is using the Base24 OneDark theme

**Comment by Binaryify** [comment]
i see

**Comment by Binaryify** [comment]
will use your terminal color config, I think you did a good job

**Comment by FredHappyface** [comment]
Thank you. I'll drop a copy of the colours here 

Order is red, yellow, green, cyan, blue, purple followed by bright
```yaml
base08: "e05561"
base09: "d18f52"
base0B: "8cc265"
base0C: "42b3c2"
base0D: "4aa5f0"
base0E: "c162de"
base0F: "bf4034"
base10: "21252b"
base11: "181a1f"
base12: "ff616e"
base13: "f0a45d"
base14: "a5e075"
base15: "4cd1e0"
base16: "4dc4ff"
base17: "de73ff"
```

Hope this helps 😊
