### ISSUE TITLE
No syntax highlight when used with Even Better TOML

### ISSUE THREAD

**Issue by QuarticCat** [Binaryify/OneDark-Pro#759]
See https://github.com/tamasfe/taplo/issues/276

Consider giving `support.type.property-name.toml` the same color as `support.type.property-name.json`?

**Comment by Binaryify** [comment]
could you provide some code

**Comment by QuarticCat** [comment]
```toml
[package]
name = "test"
version = "0.1.0"
```

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/188271866-99cf5d39-f5aa-4e7c-a4d1-03749d515c6c.png)
how about this

**Comment by QuarticCat** [comment]
Looks great!

**Comment by Binaryify** [comment]
plz check v3.15.3~

**Comment by QuarticCat** [comment]
```toml
[package]
name = "test"
version = "0.1.0"

authors = ["QC <QuarticCat@protonmail.com>"]
description = "this msg is only for testing"
edition = "2021"

[dependencies]
flume = "0.10.13"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.19.2", features = ["full"] }
```

![image](https://user-images.githubusercontent.com/70888415/188308408-931acec4-265a-4abc-ac90-4daafbd6fc63.png)

![image](https://user-images.githubusercontent.com/70888415/188308453-07a91906-1388-4198-81ac-b4e79fd26fce.png)

I'm not sure if it is Even Better TOML's problem or One Dark Pro's.

**Comment by QuarticCat** [comment]
Wait, I figured it out. Seems I should blame rust-analyzer.

**Comment by Binaryify** [comment]
@QuarticCat that is semantic highlight issue, plz check v3.15.4~

**Comment by QuarticCat** [comment]
Here is a more comprehensive example:

```toml
# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
ports = [8000, 8001, 8002]
data = [["delta", "phi"], [3.14]]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"

[[products]]
name = "Hammer"
sku = 738594937

[[products]]

[[products]]
name = "Nail"
sku = 284758393

color = "gray"
```

![image](https://user-images.githubusercontent.com/70888415/188329808-6a8f80e9-7694-4807-a3fb-d244649c19c8.png)

[Array of tables](https://toml.io/en/v1.0.0#array-of-tables) are not colored. Besides, I enabled `"editor.bracketPairColorization.enabled"` but the curly brackets are not colored as well.

I didn't realize that this problem is so complex. I should have given you this example at first. Sorry for that.

The [market place page](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) of Even Better TOML has more examples. They have more kinds of colors for different data types.
